# Generated by Django 4.2.9 on 2024-01-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_zip_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
